export default {
  login: "adirsinai",
  id: 36900949,
  node_id: "MDQ6VXNlcjM2OTAwOTQ5",
  avatar_url: "https://avatars.githubusercontent.com/u/36900949?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/adirsinai",
  html_url: "https://github.com/adirsinai",
  followers_url: "https://api.github.com/users/adirsinai/followers",
  following_url:
    "https://api.github.com/users/adirsinai/following{/other_user}",
  gists_url: "https://api.github.com/users/adirsinai/gists{/gist_id}",
  starred_url: "https://api.github.com/users/adirsinai/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/adirsinai/subscriptions",
  organizations_url: "https://api.github.com/users/adirsinai/orgs",
  repos_url: "https://api.github.com/users/adirsinai/repos",
  events_url: "https://api.github.com/users/adirsinai/events{/privacy}",
  received_events_url: "https://api.github.com/users/adirsinai/received_events",
  type: "User",
  site_admin: false,
  name: "Adir Sinai",
  company: null,
  blog: "adirsinai.com",
  location: "israel",
  email: null,
  hireable: null,
  bio: "Front End Developer",
  twitter_username: "adirsinai",
  public_repos: 15,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2018-02-27T20:43:47Z",
  updated_at: "2022-02-13T14:58:25Z",
};
